#!/bin/bash

######################
## SETTING DEFAULTS ##
######################

queue="elephant"  ## QUEUE NAME            ##
wall="24:00:00"   ## WALL-CLOCK, FOR IF... ##
procs=1           ## NUMBER OF PROCESSORS  ##
Cluster_Memory=10 ## MEMORY IN GB          ##


#####################
## OPTIONS (FLAGS) ##
#####################

while getopts "q:w:p:m:" option
do
    case $option in
        p ) procs=$OPTARG ;;
        q ) queue=$OPTARG ;;
        w ) wall=$OPTARG ;;
        m ) Cluster_Memory=$OPTARG ;;
        \?) echo "Invalid option -$option"; exit 1;;
        : ) echo "Missing option argument for -$option"; exit 1;;
    esac
done

shift $(($OPTIND-1)) ## SHIFT POSITIONAL PARAMETERS (FOR IF REQUIRED) ##


##############################
## INFO PRINTED ON TERMINAL ##
##############################

echo " --- Submitting Gaussian 16 job: $1 ---"


##################################
## CREATING LAUNCHER (.SH) FILE ##
##################################

echo '#! /bin/bash -l' > $1.sh
echo "#SBATCH -p ${queue}" >> $1.sh
echo "#SBATCH -N 1" >> $1.sh                       ## NUMBER OF NODES, NEVER MULTINODE WITH THIS CODE                    ##
echo "#SBATCH --ntasks-per-node=${procs}" >> $1.sh ## NUMBER OF CORES                                                    ##
echo "#SBATCH -t ${wall}" >> $1.sh                 ## WALLTIME, FOR IN THE CLUSTER NEEDS IT OR JUST USED FOR BACKFILLING ##
echo "#SBATCH --mem ${Cluster_Memory}G" >> $1.sh   ## RAM MEMORY ASKED TO THE CLUSTER                                    ##
echo " " >> $1.sh

echo "module load g16_a03" >> $1.sh                ## LOADING THE GAUSSIAN16 MODULE                                      ##
echo " " >> $1.sh 

echo "g16 $1" >> $1.sh 
echo " " >> $1.sh


############
## SUBMIT ##
############

sbatch $1.sh
