#!/bin/bash

######################
## SETTING DEFAULTS ##
######################

queue="elephant"  ## QUEUE NAME            ##
wall="24:00:00"   ## WALL-CLOCK, FOR IF... ##
procs=1           ## NUMBER OF PROCESSORS  ##
Cluster_Memory=10 ## MEMORY IN GB          ##


#####################
## OPTIONS (FLAGS) ##
#####################

while getopts "q:w:p:m:" option
do
    case $option in
        p ) procs=$OPTARG ;;
        q ) queue=$OPTARG ;;
        w ) wall=$OPTARG ;;
        m ) Cluster_Memory=$OPTARG ;;
        \?) echo "Invalid option -$option"; exit 1;;
        : ) echo "Missing option argument for -$option"; exit 1;;
    esac
done

shift $(($OPTIND-1)) ## SHIFT POSITIONAL PARAMETERS (FOR IF REQUIRED) ##


##############################
## INFO PRINTED ON TERMINAL ##
##############################

echo " --- Submitting APOST-3D job: $1 ---"


##################################
## CREATING LAUNCHER (.SH) FILE ##
##################################

echo '#! /bin/bash -l' > $1.sh
echo "#SBATCH -p ${queue}" >> $1.sh
echo "#SBATCH -N 1" >> $1.sh                       ## NUMBER OF NODES, NEVER MULTINODE WITH THIS CODE                    ##
echo "#SBATCH --ntasks-per-node=${procs}" >> $1.sh ## NUMBER OF CORES                                                    ##
echo "#SBATCH -t ${wall}" >> $1.sh                 ## WALLTIME, FOR IN THE CLUSTER NEEDS IT OR JUST USED FOR BACKFILLING ##
echo "#SBATCH --mem ${Cluster_Memory}G" >> $1.sh   ## RAM MEMORY ASKED TO THE CLUSTER                                    ##
echo " " >> $1.sh

echo "module load compiler/latest" >> $1.sh        ## LOADING MODULE FOR THE COMPILERS                                   ##
echo "module load mkl/latest" >> $1.sh             ## LOADING MODULE FOR MKL LIBRARIES                                   ##
echo " " >> $1.sh 

echo "export OMP_NUM_THREADS=${procs}" >> $1.sh    ## FOR PARALLELIZATION PURPOSES                                       ##
echo "export KMP_STACKSIZE=100m" >> $1.sh          ## LARGE STACKSIZE FOR IF REQUIRED (IQA NEEDS IT, FOR EXAMPLE)        ##
echo "ulimit -s unlimited" >> $1.sh                ## SETTING TO UNLIMITED, FOR IF NOT DONE BY DEFAULT IN THE CLUSTER    ##
echo " " >> $1.sh 

echo "/home/mgimferrer/APOST3D/apost3d ${1} > ${1}.apost" >> $1.sh 
echo " " >> $1.sh 


############
## SUBMIT ##
############

sbatch $1.sh
